unstable_features = true
brace_style="AlwaysNextLine"
combine_control_expr=false
control_brace_style="AlwaysNextLine"
empty_item_single_line=true
force_multiline_blocks=true
format_strings=true
hard_tabs=true
merge_imports=true
newline_style="Unix"
normalize_comments=true
normalize_doc_attributes=true
reorder_impl_items=true
space_after_colon=true
struct_lit_single_line=true
trailing_semicolon=true
use_field_init_shorthand=true
use_try_shorthand=true
wrap_comments=true
match_block_trailing_comma=true