use duplicate::duplicate;
pub struct SomeName1();
pub struct SomeName2();
pub struct SomeName3();
pub struct SomeName1();
pub struct SomeName2();
pub struct SomeName3();
pub struct SomeName4();
pub struct SomeName1(SomeMember1);
pub struct SomeName1(SomeMember2);
pub struct SomeName2(SomeMember1);
pub struct SomeName2(SomeMember2);
pub struct SomeName1(SomeMember1);
pub struct SomeName1(SomeMember2);
pub struct SomeName2(SomeMember1);
pub struct SomeName2(SomeMember2);
