use duplicate::*;
pub struct SomeName1();
pub struct SomeName2();
pub struct SomeName3();
pub struct SomeName4();
pub struct SomeName5();
pub struct SomeName6();
pub struct SomeName7();
pub struct SomeName8(SomeMember10);
pub struct SomeName8(SomeMember11);
pub struct SomeName9(SomeMember10);
pub struct SomeName9(SomeMember11);
pub struct SomeName12(SomeMember14);
pub struct SomeName12(SomeMember15);
pub struct SomeName13(SomeMember14);
pub struct SomeName13(SomeMember15);
